//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timeline.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("timeline.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt; Timeline Web Application &lt;/title&gt;
        ///  &lt;style&gt;
        ///      h3
        ///       {
        ///         text-align:right;
        ///         margin-right: 50px;
        ///         font-family: Arial, sans-serif;
        ///         font-size: 20px
        ///       }
        ///    &lt;/style&gt;
        ///	 &lt;style&gt;
        ///      h1
        ///	{
        ///		text-align:left;
        ///		margin-left: 10px;
        ///		font-family: Arial, sans-serif;
        ///		font-size: 10px;
        ///	}
        ///	&lt;/style&gt;
        ///
        ///  &lt;h1&gt;$&lt;/h1&gt;
        ///  &lt;h3 id=&quot;demo&quot; class = &quot;pos_left&quot; &gt; &lt;/h3&gt;
        ///  &lt;/head&gt;  
        ///    &lt;style ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLPART1 {
            get {
                return ResourceManager.GetString("HTMLPART1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt; Timeline Web Application &lt;/title&gt;
        ///  &lt;style&gt;
        ///      h3
        ///       {
        ///         text-align:right;
        ///         margin-right: 50px;
        ///         font-family: Arial, sans-serif;
        ///         font-size: 20px
        ///       }
        ///    &lt;/style&gt;
        ///	 &lt;style&gt;
        ///      h1
        ///	{
        ///		text-align:left;
        ///		margin-left: 10px;
        ///		font-family: Arial, sans-serif;
        ///		font-size: 10px;
        ///	}
        ///	&lt;/style&gt;
        ///
        ///  &lt;h1&gt;$&lt;/h1&gt;
        ///  &lt;h3 id=&quot;demo&quot; class = &quot;pos_left&quot; &gt; &lt;/h3&gt;
        ///  &lt;/head&gt;  
        ///    &lt;style ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLPART11 {
            get {
                return ResourceManager.GetString("HTMLPART11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       // -------------------------------------------------------------------------------
        /// 
        ///       //  A BASIC CLICK HANDLER SHOWING NAMED MARKERS - NOT USED VER 10
        ///
        ///        function showMarker()
        ///          {
        ///                  if (count == 0)
        ///                   {
        ///                     map.panTo(myMarker.getPosition());
        ///                     myMarker.setMap(map);
        ///                    count++;
        ///                   } else {
        ///                      map.panTo(nextMarker.getPosition());
        ///                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLPART2 {
            get {
                return ResourceManager.GetString("HTMLPART2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       // -------------------------------------------------------------------------------
        /// 
        ///       //  A BASIC CLICK HANDLER SHOWING NAMED MARKERS - NOT USED VER 10
        ///
        ///        function showMarker()
        ///          {
        ///                  if (count == 0)
        ///                   {
        ///                     map.panTo(myMarker.getPosition());
        ///                     myMarker.setMap(map);
        ///                    count++;
        ///                   } else {
        ///                      map.panTo(nextMarker.getPosition());
        ///                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLPART21 {
            get {
                return ResourceManager.GetString("HTMLPART21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time_machine {
            get {
                object obj = ResourceManager.GetObject("time_machine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon time_machine1 {
            get {
                object obj = ResourceManager.GetObject("time_machine1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Courier New;}{\f1\fnil Courier New;}}
        ///{\colortbl ;\red0\green0\blue255;\red0\green0\blue0;\red0\green77\blue187;}
        ///\viewkind4\uc1\pard\sa200\sl276\slmult1\lang9\b\f0\fs28 USING TIMELINE\par
        ///\pard\sa200\sl276\slmult1\qc\fs20 ver 1026\par
        ///\pard\sa200\sl276\slmult1\ul\fs22\par
        ///(1) INTRODUCTION\par
        ///\ulnone This program displays events from a GEDCOM file chronologically on Google Maps. Depending on settings, these can include Births, Baptisims, Marri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TIMELINE_HELP_FILE {
            get {
                return ResourceManager.GetString("TIMELINE_HELP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Courier New;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///\viewkind4\uc1\pard\sl240\slmult1\lang9\ul\b\f0\fs20 TERMS OF SERVICE\par
        ///\par
        ///\ulnone\b0 This software uses the Google Maps API. By using this implementation, you agree to be bound by those terms, as specified here :\par
        ///https://developers.google.com/maps/terms\par
        ///\par
        ///\ul\b LICENSE \par
        ///\ulnone\b0\par
        ///GNU Public License V3\par
        ///\par
        ///HC Williams (C) 2017\par
        ///\par
        ///This program [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TIMELINELICENSE {
            get {
                return ResourceManager.GetString("TIMELINELICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_icon {
            get {
                object obj = ResourceManager.GetObject("tree_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_icon1 {
            get {
                object obj = ResourceManager.GetObject("tree_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
